services:
  db:
    image: postgres:14.18-bookworm
    container_name: saamDatabase
    environment:
      - POSTGRES_DB=saamTest
      - POSTGRES_USER=saamUser
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    expose:
      - "5432"
  api:
    image: eclipse-temurin:25-jdk-alpine
    container_name: saamApi
    volumes:
      - ./saamTestProject/target/saamTestProject-0.0.1-SNAPSHOT.jar:/app/saamApi.jar
    command: [ "java", "-jar", "/app/saamApi.jar"]
    ports:
      - "8080:8080"
    expose:
      - '8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/saamTest
      - SPRING_DOCKER_PORT=8081
    depends_on:
      - db

  front-end:
    container_name: saamFrontend
    image: saam-frontend
    build:
      context: ./saamTestProjectFront/saamFrontendApp
    ports:
      - "8081:8081"
    depends_on:
      - api